### ISSUE TITLE
Dependency on OpenG2P packages?

### ISSUE THREAD

**Issue by poVoq** [openspp-project/openspp-program#10]
Hello :) Really nice Initiative!

I tried testing the OpenSPP packages on my Odoo15 test installation, but it looks like they have still a lot of dependencies on the OpenG2P repos.

Are you planning to port all these G2P addons over or is it intended to stay an external dependency?

**Comment by jeremi** [comment]
Sorry for the delay @poVoq. 
Yes, you can install them, you need those two:
- https://github.com/OpenG2P/openg2p-registry
- https://github.com/OpenG2P/openg2p-program

They will stay seperate. We are helping maintain them.

Otherwise, you can use this docker setup:
- https://github.com/openspp-project/openspp-docker
